### ISSUE TITLE
グローバル変数をあまり多用すべきではない

### ISSUE THREAD

**Issue by Nobu19800** [koichirokato/HumanFollwingSystem#1]
object_tacking_concierge.cppでグローバル変数を多用していますが、クラスのメンバ変数でも問題ないようなのでメンバ変数に変更したほうがいいと思います。1つのプロセスで複数のRTCを起動する場合があるのでバグになる可能性があります。

またonExecute関数が600行以上もあります。これだけ長いと可読性、保守性が悪くなるため、複数の関数に分けたほうがいいと思います。

**Comment by koichirokato** [comment]
ご指摘ありがとうございます。このRTCは、今回新規に作成したものではなく、既存のものであるため、今後の修整対象にする予定です。ご了承下さい。

**Comment by Nobu19800** [comment]
以下のページにはobject_tacking_conciergeは新規コンポーネントと記載してあります。

- https://openrtm.org/openrtm/ja/project/predictionfollowingrobot

**Comment by koichirokato** [comment]
失礼致しました。誤植でしたので訂正します。
ご指摘ありがとうございます。

**Comment by koichirokato** [comment]
修正が終わっていましたのでcloseさせていただきます
