### ISSUE TITLE
ポートの接続、RTCのアクティブ化を自動化できないか？

### ISSUE THREAD

**Issue by Nobu19800** [koichirokato/HumanFollwingSystem#3]
マニュアルにはRT System Editor上でポートを接続するように書いてありますが、これは大変なのでrtshellを使うか、あるいはOpenRTM-aist 1.2からはrtc.confの設定でポートの接続ができるのでそれを利用したほうがいいと思います。

**Comment by koichirokato** [comment]
ご指摘ありがとうございます。
今回はrtshellで対応させていただきました。
rtc.confの設定については存じませんでした。ご教示いただき、ありがとうございました。

よろしくお願いします。

**Comment by koichirokato** [comment]
修正が終わっていましたのでcloseします。
今上がっているrtshellを使用したbatファイル、マニュアル等をご確認ください。
